// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYEEjIWv3ePGdblxQD0lgF0ty0jr6Bezo',
    appId: '1:334128634624:web:7f1535384f82aa9133f1e5',
    messagingSenderId: '334128634624',
    projectId: 'food-delivery-app-ed245',
    authDomain: 'food-delivery-app-ed245.firebaseapp.com',
    storageBucket: 'food-delivery-app-ed245.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7bpranXiLZuhgFgJa50zf7hhwBhOOoI0',
    appId: '1:334128634624:android:9947a4be05f3bc3333f1e5',
    messagingSenderId: '334128634624',
    projectId: 'food-delivery-app-ed245',
    storageBucket: 'food-delivery-app-ed245.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfO0fHtGP5TW_90RngvuSM9Oiw58k5vkY',
    appId: '1:334128634624:ios:c8f3570c293d002333f1e5',
    messagingSenderId: '334128634624',
    projectId: 'food-delivery-app-ed245',
    storageBucket: 'food-delivery-app-ed245.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfO0fHtGP5TW_90RngvuSM9Oiw58k5vkY',
    appId: '1:334128634624:ios:c8f3570c293d002333f1e5',
    messagingSenderId: '334128634624',
    projectId: 'food-delivery-app-ed245',
    storageBucket: 'food-delivery-app-ed245.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYEEjIWv3ePGdblxQD0lgF0ty0jr6Bezo',
    appId: '1:334128634624:web:df3d1aef1cc3856133f1e5',
    messagingSenderId: '334128634624',
    projectId: 'food-delivery-app-ed245',
    authDomain: 'food-delivery-app-ed245.firebaseapp.com',
    storageBucket: 'food-delivery-app-ed245.appspot.com',
  );
}
